### ISSUE TITLE
Provide feedback after signup

### ISSUE THREAD

**Issue by frandiox** [frandiox/vue-enterprise-boilerplate#9]
It should show some message after successful signup and change to the login form. Perhaps it could even login automatically after the signup if auth0 returns enough information/tokens.

**Comment by cvetkovskin** [comment]
#10  I added a message, notifying the user just before logging him in. Hope it's ok.

**Comment by frandiox** [comment]
@cvetkovskin Thanks, looks good! For the next time, you can add `Closes #9` to the PR body and it will close this issue automatically :)
